export const DEFAULT_SESSION_COOKIE_NAME = "orvex.sid";

export const SESSION_KEY_PREFIX = "sess:";

export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION: "VALIDATION",
  RATE_LIMIT: "RATE_LIMIT",
  INTERNAL: "INTERNAL",
  ACCOUNT_BANNED: "ACCOUNT_BANNED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  ACCOUNT_PENDING_DELETION: "ACCOUNT_PENDING_DELETION",
  MFA_REQUIRED: "MFA_REQUIRED",
  MFA_PENDING: "MFA_PENDING",
  CONFLICT: "CONFLICT",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
